# Generated by Django 5.0.4 on 2024-04-23 13:11

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=blog.models.get_first_category, on_delete=django.db.models.deletion.PROTECT, related_name='category_posts', to='blog.categories'),
        ),
    ]
